### ISSUE TITLE
Reporte de Práctica 6

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-6-contratos-inteligentes-bjny-huerto#1]
Anexo reporte de Práctica.
[Informe P6 - S3ISOF.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-contratos-inteligentes-bjny-huerto/files/8911384/Informe.P6.-.S3ISOF.pdf)

**Comment by Rosa218** [comment]
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
